language: objective-c
gemfile:
  - Gemfile
before_install:
    - (ruby --version)
    - sudo chown -R travis ~/Library/RubyMotion
    - mkdir -p ~/Library/RubyMotion/build
    - sudo motion update --cache-version=2.38
script:
    - bundle install
    - bundle exec rake clean
    - bundle exec rake pod:install
    - bundle exec rake spec
